# Generated by Django 5.0.7 on 2024-07-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='enginner',
            new_name='engineer',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='is_resolveld',
            new_name='is_resolved',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=5),
        ),
    ]
